config/routes.rb
Rails.application.routes.draw do
  get '/', to: "welcome#index", as: 'root'

  get '/auth/:spotify/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/dashboard', to: "users#show", as: "dashboard"


  resources :playlists, only: [:index]
  get '/playlists/:playlist(/:id)', to: "playlists#show", as: "playlist"

  get '/tracks/:track(/:id)', to: "tracks#show", as: "track"

  mount ActionCable.server, at: '/cable'
  post "message", to: "messages#create"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist
  attr_reader :name, :images, :popularity, :genres, :follow_count, :href, :uid 

  def initialize(data)
    @name = data[:name]
    @images = data[:images]
    @popularity = data[:popularity]
    @genres = data[:genres]
    @follow_count = data[:followers][:total]
    @href = data[:href]
    @uid = data[:id]
  end 

end 

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  validates_presence_of :body
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/playlist.rb
class Playlist
  attr_reader :name, :collaborative, :images, :public,
              :tracks, :track_count, :type, :id
  
  def initialize(info)
    @id = info[:id]
    @name = info[:name]
    @collaborative = info[:collaborative]
    @images = info[:images]
    @public = info[:public]
    @tracks = info[:tracks][:href]
    @track_count = info[:tracks][:total]
    @type = info[:type]
  end

  def compress_name
    collapsed_name = name.tr(" ", "-")
    collapsed_name.tr(".", "")
  end   
end 

app/models/track.rb
class Track
  attr_reader :title, :artist, :album, :cover_url, :id, :stats
  def initialize(data, stats = nil)
    @id = data[:id]
    @title = data[:name]
    @artist = data[:artists][0][:name]
    @album = data[:album][:name]
    @cover_url = data[:album][:images][1][:url]
    @stats = stats
  end

  def compress_title
    compressed_name = title.tr(" ", "-")
    compressed_name.tr(".", "")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates_presence_of :username, :spotify_token, :profile_url, :token_expire
  validates_uniqueness_of :username

  def token_expired?
    true if Time.now > token_expire
  end
end

app/models/user_facade.rb
class UserFacade
  attr_reader :user

  def initialize(user)
    @user = user
    @service = SpotifyService.new(@user)
  end

  def top_5_artists
    @top_5_artists ||= @service.top_5_artists.map do |data|
      Artist.new(data)
    end
  end

  def top_5_tracks
    @top_5_tracks ||= @service.top_5_tracks.map do |data|
      Track.new(data)
    end
  end

  def most_recent_track
    Track.new(@most_recent_track ||= @service.most_recent_track)
  end

  def playlists
    @playlist_data ||= @service.find_playlists.map do |data|
      Playlist.new(data)
    end
  end

  def playlist_stats(playlist_id)
    generate_playlist_stats(playlist_id)
    length = @hash[:length].to_f
    @hash.reduce({}) do |hash, (feature, metric)|
      hash[feature] = (metric / length).round(1)
      hash
    end
  end

  def generate_playlist_stats(playlist_id)
    playlists = @service.playlist_stats(playlist_id)
    @hash = Hash.new(0)
    length = playlists[:audio_features].length
    @hash[:length] = length
    results = playlists[:audio_features].flat_map do |metrics|
       metrics.map do |feature, metric|
        @hash[feature] += metric if (metric.class == Float || metric.class == Integer)
      end
    end
  end

  def get_playlist_tracks(playlist_id)
    @service.playlist_tracks(playlist_id).map do |track_data|
      Track.new(track_data[:track])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :expired_filter
  helper_method :current_user, :require_login

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def expired_filter
    SpotifyService.new(current_user).refresh_token if current_user && current_user.token_expired?
  end

  def require_login
    unless current_user
      flash[:notice] = "You must be signed in to visit this page."
      redirect_to '/'
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = current_user.messages.build(message_params)
    broadcast(message) if message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def broadcast(message)
    ActionCable.server.broadcast "chatroom_channel", new_message: render_message(message)
  end

  def render_message(msg_source)
    render(partial: 'message', locals: {message: msg_source})
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :require_login
  
  def index
    @playlists = UserFacade.new(current_user).playlists
  end

  def show
    @facade = UserFacade.new(current_user)
    @playlist = params[:playlist].tr("-", " ")
    @tracks = @facade.get_playlist_tracks(params[:id])
    @metrics = @facade.playlist_stats(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_exists_login if (@user = User.find_by(username: user_info[:username]))

    @user = User.new(user_info)

    successful_login if @user.save
  end

  def destroy
    session.clear
    flash[:notice] = "You are now logged out!"
    redirect_to '/'
  end

  private

  def successful_login
    flash[:success] = "Successfully signed in."
    session[:user_id] = @user.id

    redirect_to dashboard_path
  end

  def user_exists_login
    @user.update(user_info)
    successful_login
  end

  def user_info
    spotify_params(request.env['omniauth.auth'].credentials, request.env['omniauth.auth'].info)
  end

  def spotify_params(credentials, profile)
    profile["image"] ||= "https://bit.ly/2tlLmZc"
    {
      username: profile["name"],
      image_url: profile["image"],
      spotify_token: credentials["token"],
      token_expire: 55.minutes.from_now,
      refresh_token: credentials["refresh_token"],
      profile_url: profile["urls"]["spotify"]
    }
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_login

  def show
    service = SpotifyService.new(current_user)
    @track = service.get_track(params[:id], true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @facade = UserFacade.new(current_user)
    @top_5_artists = @facade.top_5_artists
    @top_5_tracks = @facade.top_5_tracks
    @most_recent_song = @facade.most_recent_track
    @messages = Message.custom_display
    @message = Message.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_path if current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuneView</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title TuneView
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    #flashes
      = semantic_flash
    .ui.fluid.container
      - if current_user
        .ui.inverted.black.top.menu
          = link_to("Home", root_path, html_options = {class: "item"})
          .right.menu
            - unless current_user
              = link_to("Sign in/Register", "/auth/spotify", html_options = {class: "item"})
            - else
              = link_to('Logout', logout_path, html_options = {class: "item"})
            = link_to('Dashboard', dashboard_path, html_options = {class: "item"})
            = link_to('Playlists', playlists_path, html_options = {class: "item"})
      = yield

app/views/messages/_message.html.haml
.event
  .content
    .summary
      %em
        = "#{message.user.username}:"
      = message.body

app/views/playlists/index.html.haml
- cache "playlists-#{@playlists.count}-#{current_user.username}" do
  .ui.grid
    .row
      .five.wide.left.aligned.column
        .ui.teal.inverted.segment
          %h1 Click a playlist for its stats!
    .row
      .playlists.four.teal.centered.link.cards
        .sixteen.wide.column
          .ui.centered.link.cards
            - @playlists.each do |playlist|
              - cache playlist.id do
                %a.teal.card{href: playlist_path(playlist.compress_name, playlist.id)}
                  .image
                    - unless playlist.track_count == 0
                      = image_tag playlist.images[0][:url]
                    - else
                      = image_tag "https://bit.ly/2tlLmZc"
                  .playlist.content
                    .playlist.header
                      =playlist.name
                    .description
                      .meta
                        Track Count: #{playlist.track_count}

app/views/playlists/show.html.haml
- cache [current_user.username, @playlist].join('-') do
  .ui.grid
    .row
      .five.wide.left.aligned.column
        .ui.teal.inverted.segment
          %h1
            = @playlist
    .row
      .ui.twelve.wide.column.centered.grid
        .ui.inverted.teal.segment
          .row
            .six.wide.column
              Moods
          .row
            .ui.grid
              .four.wide.left.floated.column
                Danceability:
                %br/
                .ui.star.rating{"data-rating": "#{(@metrics[:danceability] * 10)}", "data-max-rating": 10}
              .four.wide.left.floated.column
                Energy:
                %br/
                .ui.star.rating{"data-rating": "#{(@metrics[:energy] * 10)}", "data-max-rating": 10}
              .four.wide.left.floated.column
                Happiness:
                %br/
                .ui.star.rating{"data-rating": "#{(@metrics[:valence] * 10)}", "data-max-rating": 10}
              .four.wide.left.floated.column
                Loudness:
                %br/
                #{@metrics[:loudness] * 10} dbs (Max: 0 dbs)
          .row
            %br/
          .row
            .six.wide.column
              Musicality
          .row
            .ui.grid
              .four.wide.left.floated.column
                Instrumentalness:
                %br/
                .ui.star.rating{"data-rating": "#{(@metrics[:instrumentalness] * 10)}", "data-max-rating": 10}
              .four.wide.left.floated.column
                Average Time Signature:
                %br/
                = @metrics[:time_signature].to_i
              .four.wide.left.floated.column
                Acousticness:
                %br/
                .ui.star.rating{"data-rating": "#{(@metrics[:acousticness] * 10)}", "data-max-rating": 10}
              .four.wide.left.floated.column
                Average Tempo:
                %br/
                #{@metrics[:tempo]} bpm
    .row
      .fourteen.wide.centered.column
        %table.ui.inverted.teal.celled.table
          %thead
            %tr
              %th
                Title
              %th
                Artist
          - @tracks.each_with_index do |track, index|
            - cache "track-#{track.artist}-#{track.title}" do
              %tbody
                %tr
                  %td
                    =link_to track.title, track_path(track.compress_title, track.id), class: "track-#{index}"
                  %td
                    = track.artist
:javascript
  $('.ui.rating').rating("disable");

app/views/tracks/show.html.haml
.ui.grid
  .row
    .five.wide.left.aligned.column
      .ui.teal.inverted.segment
        %h3 Title: #{@track.title}
        %h3 Artist: #{@track.artist}
        %h3 Album: #{@track.album}
        =image_tag @track.cover_url
    .five.wide.right.aligned.column
      .ui.teal.inverted.segment
        - @track.stats.each do |stat, value|
          .stat{class: stat} #{stat}: #{value}

app/views/users/show.html.haml
- cache current_user.username do
  .ui.grid
    .row
      .five.wide.left.aligned.column
        .ui.teal.inverted.segment
          %h1 Welcome, #{current_user.username}
          %img{src: current_user.image_url, width: 150, height: 150}
    .row
      .four.wide.column
        .ui.teal.inverted.raised.segment#most-recent
          .ui.items
            %h3 Your most recently played song:
            .item
              .image
                = image_tag "#{@most_recent_song.cover_url}"
              .content.card-text
                .header.card-text= @most_recent_song.title
                .meta.card-text
                  %span by: #{@most_recent_song.artist}
                .extra.card-text= @most_recent_song.album

      .four.wide.column
        .ui.fluid.raised.card.chatbox
          .content#msgs
            .ui.small.feed#message-container
              = render @messages
          .extra.content
            = form_for :message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true do |f|
              .field
                .ui.fluid.icon.input
                  = f.text_field :body
                  = f.button '<i class="bordered inverted teal edit icon"></i>'.html_safe
      .four.wide.column
        .ui.teal.inverted.raised.segment#top-5-tracks
          %h3 Top 5 Tracks of the past month:
          %ol
            - @top_5_tracks.each_with_index do |track, index|
              %li
                = link_to track.title, track_path(track.compress_title, track.id), class: "track-#{index}"
                %span by #{track.artist}
      .four.wide.column
        .ui.teal.inverted.raised.segment#top-5-artists
          %h3 Top 5 Artists of the past month:
          %ol
            - @top_5_artists.each do |artist|
              %li
                = artist.name

app/views/welcome/index.html.haml
.ui.huge.middle.aligned.center.aligned.grid
  .huge.column
    .ui.teal.image.header
      %h2
        .login.content
          %i.huge.spotify.icon
          Click Below To Sign Up!
          = link_to("/auth/spotify", class: "ui fluid large submit button") do
            Log in to Spotify